New URL link options to fix #117
opentexts/opentexts pull request #118
Opened 2020-09-02 12:00 UTC by stuartlewis

Required code to support the new link options, and removing an old file (search-result.php) that is no longer used.

2020-09-02 12:12 UTC, brizee requested changes

2020-09-02 12:12 UTC, brizee commented on app/Views/templates/search-results.php
> +            <a><img src="/images/txt.png" height="16" width="16" alt="" /></a>
I'd prefer to hold off merging to main until we have a suitable icon here - though with this being a fork that might not be easily achievable?

2020-09-02 12:12 UTC, brizee commented on public/scripts/SearchResults/result-view-controller.js
> +        const urls = [record.urlPDF, record.urlIIIF, record.urlPlainText, record.ALTOXML, record.urlOther];
```suggestion
        const urls = [record.urlPDF, record.urlIIIF, record.urlPlainText, record.urlALTOXML, record.urlOther];
```

This just looks like a typo - have you been able to test an ALTO XML record?

2020-09-02 12:12 UTC, brizee commented on public/scripts/SearchResults/result-view-controller.js
> +        for(let i = 0; i < 5; i++) {
```suggestion
        for(let i = 0; i < urls.length; i++) {
```

2020-09-02 12:14 UTC, stuartlewis commented on public/scripts/SearchResults/result-view-controller.js
> +        const urls = [record.urlPDF, record.urlIIIF, record.urlPlainText, record.ALTOXML, record.urlOther];
Well caught! No, we don't have any yet to test against. I also spotted I left the alt tags empty, so will correct that too.

2020-09-02 12:20 UTC, stuartlewis commented on app/Views/templates/search-results.php
> +            <a><img src="/images/txt.png" height="16" width="16" alt="" /></a>
My git skills aren't the best(!) so I'll leave it you if you think this should be pulled now, or wait. Given that the icons have their own issue (#76 ) I wonder if we should just merge this now (it's a better situation than before, even if not totally fixed)?

2020-09-03 09:55 UTC, brizee commented on app/Views/templates/search-results.php
> +            <a><img src="/images/txt.png" height="16" width="16" alt="" /></a>
Uh so I guess this goes more towards the long term technical direction of the project, so it's probably better for you to decide. There's a nice summary of Git workflows [here](https://www.atlassian.com/git/tutorials/comparing-workflows).

We're seemingly somewhere between [Feature Branch flow ](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) and [Forking flow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow). 

In both cases I'd typically look for a pull request to the main branch to contain an entire working feature or bugfix, though this also feeds a bit into a strategy where I'd like the main branch to always be (to the best of our knowledge) free of bugs and ready to deploy. That way if we have to hard pivot or deploy early (say some newspaper coverage was coming up sooner than we expected) we don't have to introduce new bugs or rush to get them fixed. Additionally, for other people working on the project - they don't have to work around bugs to get their things done.

Since I tend to operate in that mindset, I see this pull request as introducing the feature of "Support for ALTOXML and TXT links" but at the moment with a bug in it and would say that we should get the bug fixed so that we're not knowingly bringing bugs into main - in this case of course the bug is small and unlikely to affect others but it's good to just make these things habits. Ultimately though, this comes down to how you want to run the project over the long term and you can probably tell my approach is based on larger teams changing more often so it's up to you 😄

2020-09-05 14:22 UTC, stuartlewis commented on app/Views/templates/search-results.php
> +            <a><img src="/images/txt.png" height="16" width="16" alt="" /></a>
I've pushed a new 'other' icon now to cover this. #76 'Improve icons for filetypes' will make this look better though.

2020-09-05 14:32 UTC, brizee approved these changes

2020-09-05 14:57 UTC, stuartlewis commented
Starting agin with new pull request - this one has got a bit tangled with a conflict.

2020-09-05 14:57 UTC, closed without merging